[pytest]
markers =
    smoke : run smoke tests
    regression : run regressoion test

addopts =
# stops running after attempting third time
    --maxfail=3
    # verbose gives detail test case results
    -v
    # html report name and directory is mentioned
    --html=reports/reports.html
    #Embeds all styles, scripts, and content into the single HTML file
    --self-contained-html
    # Prints logs in console and report
    --capture=tee-sys